name: Blog do Tacio
description: Programação, Design & Educação
meta_description: "Programação, Design & Educação"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'taciosantosblog.github.io'
google_analytics: 'UA-79159558-2'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://taciosantosblog.github.io/'
author:         'Tacio Santos'
